module.exports = {
    LOCAL_URL : 'http://localhost:3000',
    EMAIL_ID : 'bettaboo97@gmail.com',
    EMAIL_PASS : '93682123',
    VER_EXPIRED_MESSAGE : "Token has expired. Please click this button to regenerate a token.",
    ERROR : "ERROR",
    SUCCESS : "SUCCESS",
    VER_SUCCESS : "VERIFIED SUCCESSFULLY",
    VER_UNKNOWN : "Verificatin failed. Please try again.",
    EMAIL_IMAGE_URL : "https://i.ibb.co/ZRj0XpC/121887103-spring-rolls-asian-food-with-various-ingredients-on-stone.webp",
    USER_N_EXIST : "User doesn't exist",
    INV_PASS : "Incorrect Password",
    ACTIVATE_USER : "This account is not activated. Please check your email and follow the instructions in the activation mail.",
    ERR_UNKNOWN : "Something went wrong.",
    COMPANY_EXISTS : "Company with the given COMPANY NAME already exists",
    EMAIL_EXISTS : "User with the given EMAIL ADDRESS already exists",
    DUP_KEY : "Duplicate key error",
    JWT_KEY : "khawaDawa",
    AUTH_ERR : "User is not authenticateMerchantd. Please login and try again",
    MAX_LOGIN : "You're already logged in 5 devices. You can not login from more devices",
    LOGOUT_FAILED : "Failed to logout user.",
    TOKEN_EXPIRE_TIME : 1800000,
    VERIFY_ROUTE : '/_verify',
    LOGOUT_SUCCESS : "Successfully logged out",
    DELETE_FAILED :  "Failed to delete menu. Please try again later.",
    DELETE_SUCCESS : "Menu named: @menuname was deleted." ,
    UPDATE_FAILED : "Failed to update menu.",
    INSERT_FAILED : "Failed to insert menu.",
    ITEM_ADD_FAILED: "Failed to add item to the menu.",
    ITEM_UPDATE_FAILED: "Failed to update item list.",
    ITEM_DELETE_FAILED: "Failed to delete item. Please try again later."
}

